### ISSUE TITLE
Met a little bug

### ISSUE THREAD

**Issue by zwy1996** [Eli-YiLi/WSSS_MMSeg#2]
Hi, 

nice work!

When I used your code. I got the following error. We should use the pseudo label of ppmg. and the path of label might be fixed?
such as /2009_002281.png.jpg. Would you please give me some advice?

Best wishes to you!

FileNotFoundError: [Errno 2] No such file or directory: '/JPEGImages/2009_002281.jpg /SegmentationClassAug/2009_002281.png.jpg'

**Comment by Eli-YiLi** [comment]
dataset split list format:
2007_000032
2007_000039
2007_000063
2007_000068
2007_000121
2007_000170
2007_000241
2007_000243
2007_000250
2007_000256
2007_000333
2007_000363

img format:
2007_000032.jpg

pseudo-mask format:
2007_000032.png

**Comment by Eli-YiLi** [comment]
do not use the split list of classification phase

**Comment by zwy1996** [comment]
Would please offer the split file of the WSSS_MMSeg? I was a little confused about the file directoy, specially the "data" directory

Thanks very much!

**Comment by Eli-YiLi** [comment]
The split lista are provided in the the package "Download VOC12 OneDrive, BaiduYun"

please refer the data structure to "configs/_base_/datasets/pascal_voc12_wsss.py"

**Comment by zwy1996** [comment]
Hi,

I am very sorry to bother you again, I can run experiments on the default parameter on the val dataset, Would you please tell me how to change some parameters to test on the test dataset  and I can offer the result to the pascal website.

Thank you very much!

**Comment by zwy1996** [comment]
OK, and what instructions I should run? I think maybe only test.py?

**Comment by Eli-YiLi** [comment]
use configs with "_cp.py" with params like that:

test_cfg = dict(mode='slide', crop_size=(512, 512), stride=(480, 480), crf=True,
                pred_output_path='data/voc12/VOC2012/pred')
data = dict(test=dict(split='ImageSets/Segmentation/test.txt'))
