### ISSUE TITLE
The error

### ISSUE THREAD

**Issue by zwy1996** [Eli-YiLi/WSSS_MMSeg#3]
Thanks for your code.
When I used your code, I met the following error. 

tools/slurm_train.sh: line 15: srun: command not found

I think maybe because of slurm. Would you please offer the other instructions such as "PMM", the "bash dish.sh" version

Best wishes to you!

**Comment by Eli-YiLi** [comment]
Srun is for GPU clusters, and I do not have local GPU severs.

So you can replace the "tools/slurm_train.sh" commands in "tools/run_wsss.sh" by "tools/dist_train.sh" with some little modifications.

**Comment by zwy1996** [comment]
Thank you!

I have fixed it, I can run the instructions successfully!

Best wish to you!

**Comment by zwy1996** [comment]
Hello, I was very sorry to bother you.

I met a new bug, I was some confused about it.

FileNotFoundError: [Errno 2] No such file or directory: 'data/voc12/VOC2012/cyclic_mask_r2n/2010_005035.png'

When I trained the PMM , I just used you default parameter, and I retrained the wsss_mmseg. Would you please give me some advice?
Thanks very much!

**Comment by Eli-YiLi** [comment]
"configs/pspnet_wsss/pspnet_res2net_20k_voc12aug_pus.py" uses ppmg from cls.

"cyclic_mask_r2n" is in configs/pspnet_wsss/pspnet_res2net_20k_voc12aug.py, generated by "configs/pspnet_wsss/pspnet_res2net_20k_voc12aug_cp.py" (test)

please refer to "tools/run_wsss.sh"

**Comment by zwy1996** [comment]
Thanks for your advice!

I can run normally now.

**Comment by shi-10** [comment]
> Thank you!
> 
> I have fixed it, I can run the instructions successfully!
> 
> Best wish to you!



> Thank you!
> 
> I have fixed it, I can run the instructions successfully!
> 
> Best wish to you!

Sorry to bother you, I would like to ask how to modify this part of the code without using GPU cluster, thank you
