### ISSUE TITLE
Question about COCO Pseudo Mask

### ISSUE THREAD

**Issue by lh-zhu** [Eli-YiLi/WSSS_MMSeg#6]
Hi there! Your work is so awesome at the performence! I'd like to do something on it. But when I run the code you commited, I meet some question:

1. What's the label '0' refer to in your `ppmg_coco` pseudo mask? I found that people and the background are all labeled as '0' in some pseudo masks like 000000000036.png.
2. Is that your label mapping is showed as bellow?

> CLASSES = (
>         'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
>         'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign',
>         'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep',
>         'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella',
>         'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard',
>         'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
>         'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork',
>         'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange',
>         'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair',
>         'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv',
>         'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
>         'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase',
>         'scissors', 'teddy bear', 'hair drier', 'toothbrush', 'banner',
>         'blanket', 'branch', 'bridge', 'building-other', 'bush', 'cabinet',
>         'cage', 'cardboard', 'carpet', 'ceiling-other', 'ceiling-tile',
>         'cloth', 'clothes', 'clouds', 'counter', 'cupboard', 'curtain',
>         'desk-stuff', 'dirt', 'door-stuff', 'fence', 'floor-marble',
>         'floor-other', 'floor-stone', 'floor-tile', 'floor-wood',
>         'flower', 'fog', 'food-other', 'fruit', 'furniture-other', 'grass',
>         'gravel', 'ground-other', 'hill', 'house', 'leaves', 'light', 'mat',
>         'metal', 'mirror-stuff', 'moss', 'mountain', 'mud', 'napkin', 'net',
>         'paper', 'pavement', 'pillow', 'plant-other', 'plastic', 'platform',
>         'playingfield', 'railing', 'railroad', 'river', 'road', 'rock', 'roof',
>         'rug', 'salad', 'sand', 'sea', 'shelf', 'sky-other', 'skyscraper',
>         'snow', 'solid-other', 'stairs', 'stone', 'straw', 'structural-other',
>         'table', 'tent', 'textile-other', 'towel', 'tree', 'vegetable',
>         'wall-brick', 'wall-concrete', 'wall-other', 'wall-panel',
>         'wall-stone', 'wall-tile', 'wall-wood', 'water-other', 'waterdrops',
>         'window-blind', 'window-other', 'wood')

**Comment by lh-zhu** [comment]
looking for your reply, thanks

**Comment by lh-zhu** [comment]
Do you use some chatting apps like wechat? Could we talk about more detailed things on it?

**Comment by Eli-YiLi** [comment]
1. 0 is background.
2. label_map: https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/ (range from 0-91 with bg, only 81 classes are valid)

**Comment by lh-zhu** [comment]
thanks!

**Comment by lh-zhu** [comment]
But I still have question that why the pseudo mask in foider `ppmg_coco` mislead the class `background` and `people` in a very simple image `000000000036`? And I also checked other images that contain people, their psudo mask also labeled people area as '0'.

**Comment by lh-zhu** [comment]
> * 0 is background.
> * label_map: https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/ (range from 0-91 with bg, only 81 classes are valid)

Thanks for the blog that truly helped me unstand the `coco14` dataset! I noticed that the invalid classes' num in the blog is 11 and the valid classes contains 80 ones. So should we set the `coco14`'s class_num to 92 (80 valid foregrounds + 11 invalid classes + 1 background) to get the best CAM performence?

**Comment by lh-zhu** [comment]
> > * 0 is background.
> > * label_map: https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/ (range from 0-91 with bg, only 81 classes are valid)
> 
> Thanks for the blog that truly helped me unstand the `coco14` dataset! I noticed that the invalid classes' num in the blog is 11 and the valid classes contains 80 ones. So should we set the `coco14`'s class_num to 92 (80 valid foregrounds + 11 invalid classes + 1 background) to get the best CAM performence?

Sorry, I noticed that the last invalid is not need to be add. QAQ
