### ISSUE TITLE
Question about COCO14 segmentation performence

### ISSUE THREAD

**Issue by lh-zhu** [Eli-YiLi/WSSS_MMSeg#7]
Excuse me, I still find the performence of coco is only 33.64, could you help me with some details? I run the config file `pspnet_scalenet101_40kx32_coco.py` with `val_mini.txt` split using 4 gpus. The detailed report is as below:
[20220203_085809.log](https://github.com/Eli-YiLi/WSSS_MMSeg/files/7999771/20220203_085809.log)

**Comment by Eli-YiLi** [comment]
My setting about batch size is 2img*32gpus. You need to extend the iteration and reduce lr in linear policy, if your batch size is small (2*4).

**Comment by lh-zhu** [comment]
Thank you for your help, I will try it again, and could you find that few classes in the report have 0 mIoU, 1, 80, 89, etc. Its wierd. Do you get the same result?

**Comment by Eli-YiLi** [comment]
You may firstly change the batch size and get similar results. Few or no classes are 0 mIoU.

**Comment by ZechengLi19** [comment]
> Thank you for your help, I will try it again, and could you find that few classes in the report have 0 mIoU, 1, 80, 89, etc. Its wierd. Do you get the same result?

Same question. Do you figure it out?

**Comment by Eli-YiLi** [comment]
Yes, I meet it too. But I didn't analyze the reason. You can check the existence/number/quality of these labels in pseudo-mask.

**Comment by ZechengLi19** [comment]
> Yes, I meet it too. But I didn't analyze the reason. You can check the existence/number/quality of these labels in pseudo-mask.

I have download the pseudo-mask you provided. And I visualize it. However, **it don't high light the "person" class**. Therefore, I just evaluate the performance of the "**coco_scalenet.pth**" on coco2017(download from **baiduyun**). And the log file is as follow.(ps: I know you do this work on coco2014, but I just evaluate it on coco2017, sorry).

[test_out_release.log](https://github.com/Eli-YiLi/WSSS_MMSeg/files/9593504/test_out_release.log)

**Comment by ZechengLi19** [comment]
> Yes, I meet it too. But I didn't analyze the reason. You can check the existence/number/quality of these labels in pseudo-mask.

I would appreciate it if you can check your own log file and share it with me.
